### ISSUE TITLE
如何用浏览器请求服务?

### ISSUE THREAD

**Issue by kran** [dubbo/dubbo-http-demo#5]
本地跑起来之后, 访问 http://127.0.0.1:8080/http/com.dubbo.demo.HelloService?anyhost=true&application=ws-demo&dubbo=2.4.10&interface=com.dubbo.demo.HelloService&methods=hello&pid=33755&revision=1.0.0&server=jetty&side=provider&timestamp=1468981294583&version=1.0.0 只是空页面.

**Comment by oldratlee** [comment]
这个URL是 服务Provider本身的信息 ，不是一个访问地址。

具体HTTP调用如何收发数据，可以看看实现。
